name: Build & Release Squirrel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publish Service
        run: dotnet publish ./MyService/MyService.csproj \
              -c Release -r win-x64 --self-contained false -o ./publish

      - name: Install Squirrel CLI
        run: choco install squirrel -y

      - name: Releasify
        run: |
          squirrel --releasify ./publish/MyService.exe \
                  --releaseDir ./releases \
                  --packagesDir ./publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./releases/**

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/RELEASES
          asset_name: RELEASES
          asset_content_type: application/octet-stream

      - name: Upload .nupkg and Setup.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releases/*.nupkg
          asset_name: MyService.${{ github.ref_name }}.nupkg
          asset_content_type: application/octet-stream
